# Generated by Django 6.0 on 2025-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='produit',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Image du code-barres'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='barcode',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Code-barres (12 chiffres de données)'),
        ),
    ]
